import pte from '../assets/img/pte.png';
import dashboard from '../assets/img/dash-weather.png';
import cbr from '../assets/img/cbr.png';
import fileportalDash from '../assets/img/fileportalDash.png';
import fileportal2 from '../assets/img/fileportal2.png';
import nutri from '../assets/img/nutri.png';
import moreapp from '../assets/img/moreapp.png';
import morenutri from '../assets/img/morenutri.png';
import nutrimain2 from '../assets/img/nutrimain2.png';
import shoplist1 from '../assets/img/shoplist1.png';
import shoplist2 from '../assets/img/shoplist2.png';





//TODO: get project details along with pictures from backend


export default{
    projects:[
        {
            id:1,
            title: "Weather Observation",
            description:"A web app which shows weather observations for major cities in Australia." ,
            more_info:"\"Weather Observation\" uses data provided by Bureau of Meteorology Australia (BOM) under free data service. " +
            "This web application provides weather observation generated by BOM for some of the major cities in Australia. It is build using Laravel for PHP. " +
            "The Google map and Google Charts used in the application is added via several other packages.",
            screenshots:[{
                main: dashboard,
                other_visuals: cbr
            }],
            demo:"https://bom-project.herokuapp.com/",
            sourceCode:"https://github.com/prayatna/bom-proj"

        },
        {
            id:2,
            title: "PTE Admin Panel Website",
            description:"Website for PTE practice test built with ReactJS with Redux ",
            more_info:`A website built during my internship at NOVA Software. The website was built from ground zero using ReactJS and Redux. This was a  
            "great opportunity for me to learn about react and redux as it was all new to me. The main concept of the web application was to enable administrators to manage their " +
            "PTE practice materials. They could add/remove/update the PTE questions according to different question types. As my internship was just for couple of months only the functionality for adding
            a question was implemented.`,
            screenshots:[{
                main: pte,
            }],
            demo:"",
            sourceCode:"https://github.com/prayatna/pte_admin"

        },

        {
            id:3,
            title: "NutriFinder",
            description: "Android app for getting Dietary Intake through food photographs",
            more_info: "The android based NutriFinder app was my final year project during my study of Bachelor of Software Engineering at the University of Canberra. The main aim of the" +
            "app was to take a picture of any food item and it will identify what type of food it is along with its nutritional values. The basic working mechanism is that first the app enables" +
            "the user to take a picture. The picture is then sent for identification to the Clarifai API. The API returns list of possible result but the app only display the result with the" +
            "highest confidence (must have put an option to select from the list by user). After identifying the food item, it is then sent to the Nutritionix API to get the result of the " +
            "nutritional value that particular food item contains. Finally, the result will be displayed as nutritional facts of the food item.",
            screenshots:[{
                main: nutri,
                main2:nutrimain2,
                other_visuals: moreapp,
                other_visuals2:morenutri
            }],
            demo:"",
            sourceCode:""

        },

        {
            id:4,
            title: "My Shopping List",
            description: "basic  Android app to add/remove shopping list item",
            more_info: "This basic Android application uses CRUD methods. It has taken an approach of basic To-DO list app which has similar features" +
            "In shopping list app, you can add or create, update, delete an item as shown in the screenshots. This project was built for basic understanding" +
            "of android application development during my university study.",
            screenshots:[{
                main: shoplist1,
                other_visuals: shoplist2
            }],
            demo:"",
            sourceCode:""


        },

        {
            id:5,
            title: "File Portal",
            description: "a file sharing web application made using Laravel framework",
            more_info: "a web app built using Laravel for PHP as one of my university project. This application has basic authentication which lets user register and login" +
            "Roles can be added so that only specific type of users are allowed to share/download/upload the file. The file system uses basic CRUD methods. The application" +
            "is styled using bootstrap.",
            screenshots:[{
                main: fileportalDash,
                other_visuals: fileportal2
            }],
            demo:"",
            sourceCode:""

        }
    ]
}